# Generated by Django 2.1.2 on 2018-12-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Normal'), (2, 'Farm'), (3, 'Deprecated'), (4, 'River'), (5, 'Tree')], default=0)),
                ('crop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell', to='game.Crop')),
            ],
            options={
                'verbose_name': 'Cell',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='map.Map'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('map', 'position_x', 'position_y')},
        ),
    ]
