# Generated by Django 2.1.2 on 2018-11-28 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_slot', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=40)),
                ('code', models.CharField(default='none', max_length=40)),
                ('type', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Seed'), (2, 'Resource'), (3, 'Kit'), (4, 'fruit')], default=0)),
                ('store_price', models.IntegerField(default=2)),
                ('sold_price', models.IntegerField(default=1)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('type', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Seed'), (2, 'Resource'), (3, 'Kit'), (4, 'fruit')], default='Item.UNDEFINED')),
                ('store_price', models.IntegerField(default=2)),
                ('sold_price', models.IntegerField(default=1)),
                ('display_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('generator', models.CharField(blank=True, max_length=255, null=True)),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='SeedItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Item')),
                ('crop_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.CropSpecies')),
            ],
            bases=('inventory.item',),
        ),
        migrations.AddField(
            model_name='slot',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='inventory.Item'),
        ),
    ]
