# Generated by Django 2.1.2 on 2018-11-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Growing'), (2, 'Ripening'), (3, 'Dead')], default=0)),
                ('ripening_age', models.IntegerField(default=100)),
                ('growing_speed', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ripening_age', models.IntegerField(default=100)),
                ('base_growing_speed', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='CropSpeciesRewardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('crop_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cropses', to='inventory.CropSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_slot', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Seed'), (2, 'Resource'), (3, 'Kit'), (4, 'fruit')], default=0)),
                ('store_price', models.IntegerField(default=2)),
                ('sold_price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.Inventory')),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.ItemPrototype'),
        ),
        migrations.AddField(
            model_name='cropspeciesrewarddetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='reward_choices',
            field=models.ManyToManyField(related_name='crop_species', through='inventory.CropSpeciesRewardDetail', to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='inventory.CropSpecies'),
        ),
        migrations.AlterUniqueTogether(
            name='cropspeciesrewarddetail',
            unique_together={('crop_species', 'item')},
        ),
    ]
