# Generated by Django 2.1.2 on 2018-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeditem',
            name='crop_species',
        ),
        migrations.RemoveField(
            model_name='seeditem',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='SeedItem',
        ),
    ]
