# Generated by Django 2.1.2 on 2018-11-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropspeciesrewarddetail',
            name='item_prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemPrototype'),
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='reward_choices',
            field=models.ManyToManyField(related_name='crop_species', through='game.CropSpeciesRewardDetail', to='inventory.ItemPrototype'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='game.CropSpecies'),
        ),
        migrations.AlterUniqueTogether(
            name='cropspeciesrewarddetail',
            unique_together={('crop_species', 'item_prototype')},
        ),
    ]
